"""Persistence for the Company Knowledge Vault.

Two tables, both append-only in practice.

`KnowledgeEntry` is one assertion about one company — "revenue segments are
X", "the principal risk is Y" — carrying its provenance, its confidence and
its version. A later filing does not update the row; it inserts a new one at
`version + 1` and marks the previous `superseded`. The old row keeps its
evidence forever, so "what did we believe in FY2022, and on what basis?"
remains answerable.

`DocumentSummary` is the permanent memory that makes the platform fast. Nine
summaries per document, generated once, read thereafter. Without these every
question re-reads the PDF corpus; with them the AI consults a paragraph it
already wrote and only falls through to RAG when the summary is insufficient.

Both tables record the model and prompt version that produced them, because a
summary generated by a different model is a different artefact and comparing
the two without knowing that is how a "the AI changed its mind" incident
starts.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey, Index, Integer, String, Text,
    UniqueConstraint, func,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base
# Registers the FK targets before the mapper is configured; without this the
# relationship resolves lazily and fails with NoReferencedTableError in
# whatever code happens to touch the ORM first.
from app.models.company import Company  # noqa: F401
from app.models.document import Document  # noqa: F401


class KnowledgeEntry(Base):
    """One versioned, attributed assertion in a company's vault."""

    __tablename__ = "knowledge_entries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    company_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    #: One of `VaultSection`. Closed vocabulary — see the domain module.
    section: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    #: Stable identifier for the assertion within its section, e.g.
    #: "principal_risk_1". Combined with (company, section) this is what a new
    #: filing supersedes.
    key: Mapped[str] = mapped_column(String(80), nullable=False, index=True)
    label: Mapped[str] = mapped_column(String(240), default="", nullable=False)

    #: Narrative assertions are the common case; numeric ones carry both so a
    #: reader sees the figure and the sentence it came from.
    value_text: Mapped[str | None] = mapped_column(Text)
    value_number: Mapped[float | None] = mapped_column(Float)
    unit: Mapped[str | None] = mapped_column(String(24))

    confidence: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    #: Authority of the source type, from SOURCE_AUTHORITY. Stored rather than
    #: recomputed so the ordering that produced a supersession is auditable
    #: after the table changes.
    authority: Mapped[float] = mapped_column(Float, default=0.4, nullable=False)

    # --- provenance: required, not decorative -------------------------
    document_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("documents.id", ondelete="SET NULL"), index=True,
    )
    page: Mapped[int | None] = mapped_column(Integer)
    paragraph: Mapped[int | None] = mapped_column(Integer)
    fiscal_year: Mapped[int | None] = mapped_column(Integer, index=True)
    # VAULT-001. String(4) assumed "Q1". Real extracted periods are
    # "Q1FY26", "H1FY25", "FY2026" — the extractor records the period as the
    # filing writes it, which is more useful than a bare quarter and longer
    # than four characters. Truncating would have been worse than failing.
    quarter: Mapped[str | None] = mapped_column(String(16))
    doc_type: Mapped[str | None] = mapped_column(String(40))
    #: The verbatim sentence supporting the assertion.
    evidence: Mapped[str | None] = mapped_column(Text)

    # --- versioning ---------------------------------------------------
    version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)
    status: Mapped[str] = mapped_column(
        String(12), default="current", nullable=False, index=True,
    )
    #: The entry that replaced this one. Null while current.
    superseded_by: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("knowledge_entries.id", ondelete="SET NULL"),
    )

    #: Which model and prompt produced this, when it was inferred rather than
    #: read. Two entries from different models are different artefacts.
    generated_by: Mapped[str | None] = mapped_column(String(64))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
    )

    __table_args__ = (
        # The lookup behind every vault read: current knowledge for a company.
        Index("ix_knowledge_current", "company_id", "section", "status"),
        # Version history for one assertion.
        Index("ix_knowledge_lineage", "company_id", "section", "key", "version"),
        UniqueConstraint("company_id", "section", "key", "version",
                         name="uq_knowledge_version"),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (f"<KnowledgeEntry {self.section}.{self.key} "
                f"v{self.version} {self.status}>")


class DocumentSummary(Base):
    """One permanent AI summary of one document.

    The read-first memory. Nine kinds per document, generated once and reused,
    so a question about a company consults prose the platform already wrote
    rather than re-parsing hundreds of pages.
    """

    __tablename__ = "document_summaries"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    document_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )
    company_id: Mapped[str] = mapped_column(
        String(36), ForeignKey("companies.id", ondelete="CASCADE"),
        nullable=False, index=True,
    )

    #: One of `SummaryKind`.
    kind: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    word_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)

    #: Period the underlying document reports on, so temporal queries can
    #: order summaries without re-reading the documents.
    fiscal_year: Mapped[int | None] = mapped_column(Integer, index=True)
    quarter: Mapped[str | None] = mapped_column(String(16))
    doc_type: Mapped[str | None] = mapped_column(String(40), index=True)

    #: Provider and model, so a later regeneration is comparable and a
    #: model change is visible rather than inferred.
    provider: Mapped[str | None] = mapped_column(String(32))
    model: Mapped[str | None] = mapped_column(String(64))
    prompt_version: Mapped[int] = mapped_column(Integer, default=1, nullable=False)

    #: True when the summary was produced without a live model — the offline
    #: composer. Recorded so template prose is never mistaken for analysis.
    is_fallback: Mapped[bool] = mapped_column(
        Boolean, default=False, nullable=False,
    )

    prompt_tokens: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(
        Integer, default=0, nullable=False,
    )
    cost_usd: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False,
    )

    __table_args__ = (
        # One summary of each kind per document per prompt version. A prompt
        # revision produces a new row rather than overwriting the old one, so
        # a regression in prompt wording stays diagnosable.
        UniqueConstraint("document_id", "kind", "prompt_version",
                         name="uq_summary_doc_kind_version"),
        Index("ix_summary_company_kind", "company_id", "kind"),
        Index("ix_summary_temporal", "company_id", "fiscal_year", "kind"),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<DocumentSummary doc={self.document_id} {self.kind}>"
