"""The migrations must produce the schema the models declare.

This suite exists because a defect reached production that every other test
was structurally incapable of catching.

The test suite builds its database with `Base.metadata.create_all()`, which
derives the schema *from the models*. Production builds its database by
running the Alembic migrations. Those are two independent descriptions of the
same thing, and nothing compared them — so a hand-written migration that
omitted the `created_at`/`updated_at` columns `Base` gives every table passed
2,253 tests locally and then failed on the first query in production with
`UndefinedColumn`.

The fix is not "be more careful writing migrations". It is to run the
migrations into an empty database and diff the result against the models,
which is what this does.
"""
from __future__ import annotations

import pathlib
import re

import pytest
import sqlalchemy as sa

BACKEND = pathlib.Path(__file__).resolve().parent.parent
VERSIONS = BACKEND / "alembic" / "versions"

#: Columns `Base` declares for every table. A migration that creates a table
#: without them produces a schema the ORM cannot query.
INHERITED_COLUMNS = ("created_at", "updated_at")


def _migration_files() -> list[pathlib.Path]:
    return sorted(p for p in VERSIONS.glob("*.py") if not p.name.startswith("__"))


class TestMigrationChain:
    """Structural checks that need no database."""

    def test_migrations_exist(self):
        assert _migration_files(), "no migration files found"

    def test_every_migration_declares_a_revision(self):
        for path in _migration_files():
            text = path.read_text()
            # Alembic's autogenerated files annotate the type
            # (`revision: str = '...'`); hand-written ones do not.
            assert re.search(r"^revision(?:\s*:[^=]+)?\s*=", text, re.M), (
                f"{path.name}: no revision"
            )
            assert re.search(r"^down_revision(?:\s*:[^=]+)?\s*=", text, re.M), (
                f"{path.name}: no down_revision"
            )

    def test_the_chain_is_linear_and_complete(self):
        """Exactly one root, no orphans, no forks."""
        revisions: dict[str, str | None] = {}
        for path in _migration_files():
            text = path.read_text()
            rev = re.search(
                r"^revision(?:\s*:[^=]+)?\s*=\s*[\"'](\w+)[\"']", text, re.M
            )
            down = re.search(
                r"^down_revision(?:\s*:[^=]+)?\s*=\s*(?:[\"'](\w+)[\"']|None)",
                text, re.M,
            )
            assert rev, f"{path.name}: unparseable revision"
            revisions[rev.group(1)] = down.group(1) if down and down.group(1) else None

        roots = [r for r, d in revisions.items() if d is None]
        assert len(roots) == 1, f"expected one root migration, found {roots}"

        parents = [d for d in revisions.values() if d is not None]
        assert len(parents) == len(set(parents)), (
            "two migrations share a parent — the chain has forked"
        )
        for rev, down in revisions.items():
            if down is not None:
                assert down in revisions, f"{rev} points at missing parent {down}"

    def test_a_created_table_carries_the_inherited_audit_columns(self):
        """The defect that reached production.

        `Base` declares created_at/updated_at on every model. A migration that
        calls `create_table` without them yields a schema the ORM cannot
        query — and `create_all()`, which the rest of the suite uses, would
        never reveal it.
        """
        offenders: list[str] = []
        for path in _migration_files():
            text = path.read_text()
            for match in re.finditer(
                r'op\.create_table\(\s*"(\w+)"(.*?)\n    \)', text, re.S
            ):
                table, body = match.group(1), match.group(2)
                if table in {"alembic_version"}:
                    continue
                for column in INHERITED_COLUMNS:
                    if f'"{column}"' not in body:
                        offenders.append(f"{path.name}:{table} missing {column}")
        assert not offenders, (
            "migrations create tables without the audit columns Base "
            f"declares: {offenders}"
        )


class TestMigrationsMatchModels:
    """Run the migrations for real and diff against the models."""

    @pytest.fixture(scope="class")
    def migrated(self, tmp_path_factory):
        """An empty database with every migration applied."""
        from alembic import command
        from alembic.config import Config

        target = tmp_path_factory.mktemp("mig") / "migrated.db"
        url = f"sqlite:///{target}"

        # `alembic/env.py` deliberately ignores the ini URL and reads
        # `settings.DATABASE_URL`, so that production cannot be pointed at the
        # wrong database by an ini file. Patching the setting is therefore the
        # only way to migrate into a scratch database — setting
        # `sqlalchemy.url` alone silently migrates whatever the app is
        # configured for, which is how this fixture first "passed" by
        # replaying migrations over an existing SQLite file.
        from app.core.config import settings

        original = settings.DATABASE_URL
        config = Config(str(BACKEND / "alembic.ini"))
        config.set_main_option("script_location", str(BACKEND / "alembic"))
        config.set_main_option("sqlalchemy.url", url)
        try:
            settings.DATABASE_URL = url
            command.upgrade(config, "head")
        except Exception as exc:  # pragma: no cover - surfaced as a skip
            pytest.skip(f"migrations could not run in this environment: {exc}")
        finally:
            settings.DATABASE_URL = original
        return sa.create_engine(url)

    def _model_metadata(self):
        import importlib
        import pkgutil

        import app.models
        from app.db.base import Base

        for module in pkgutil.iter_modules(app.models.__path__):
            importlib.import_module(f"app.models.{module.name}")
        return Base.metadata

    def test_every_model_table_exists_after_migrating(self, migrated):
        metadata = self._model_metadata()
        actual = set(sa.inspect(migrated).get_table_names())
        missing = sorted(set(metadata.tables) - actual)
        assert not missing, f"tables declared by models but never migrated: {missing}"

    def test_every_model_column_exists_after_migrating(self, migrated):
        """The check that would have caught the production failure."""
        metadata = self._model_metadata()
        inspector = sa.inspect(migrated)
        available = set(inspector.get_table_names())

        problems: list[str] = []
        for name, table in metadata.tables.items():
            if name not in available:
                continue
            actual = {c["name"] for c in inspector.get_columns(name)}
            for column in table.columns:
                if column.name not in actual:
                    problems.append(f"{name}.{column.name}")
        assert not problems, (
            "columns the models declare that the migrations do not create: "
            f"{sorted(problems)}"
        )

    def test_the_filing_collection_tables_are_queryable(self, migrated):
        """A regression guard naming the tables that actually broke."""
        inspector = sa.inspect(migrated)
        for table in ("discovered_filings", "company_crawl_state"):
            assert table in inspector.get_table_names(), f"{table} not migrated"
            columns = {c["name"] for c in inspector.get_columns(table)}
            for column in INHERITED_COLUMNS:
                assert column in columns, f"{table}.{column} missing"
