"""initial schema: modules 1-10

Revision ID: 33573f2f567a
Revises: 
Create Date: 2026-07-30 20:56:40.520828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33573f2f567a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_prompts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('style', sa.String(length=32), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('edited_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'version', name='uq_prompt_key_version')
    )
    with op.batch_alter_table('ai_prompts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_prompts_key'), ['key'], unique=False)
        batch_op.create_index('ix_prompt_active', ['key', 'is_active'], unique=False)

    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_owner'), ['owner'], unique=False)
        batch_op.create_index('ix_usage_owner_provider', ['owner', 'provider'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=254), nullable=True),
    sa.Column('actor_role', sa.String(length=24), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('summary', sa.String(length=500), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('request_id', sa.String(length=36), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_category_time', ['category', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_audit_tenant_time', ['tenant_id', 'occurred_at'], unique=False)

    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=32), nullable=True),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=64), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_run_after'), ['run_after'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_job_poll', ['status', 'priority', 'run_after'], unique=False)
        batch_op.create_index('ix_job_tenant_kind', ['tenant_id', 'kind'], unique=False)

    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backup_records_finished_at'), ['finished_at'], unique=False)

    op.create_table('benchmark_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'as_of', name='uq_benchmark_symbol_date')
    )
    with op.batch_alter_table('benchmark_levels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_levels_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_levels_symbol'), ['symbol'], unique=False)

    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'event_id', name='uq_billing_event')
    )
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_billing_events_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_billing_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('sector', sa.String(length=120), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=300), nullable=True),
    sa.Column('incorporated_year', sa.Integer(), nullable=True),
    sa.Column('data_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin'),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_company_ticker_exchange')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_company_sector_mcap', ['sector', 'market_cap'], unique=False)

    op.create_table('error_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('exc_type', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('route', sa.String(length=160), nullable=True),
    sa.Column('method', sa.String(length=8), nullable=True),
    sa.Column('stack', sa.Text(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('last_request_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('error_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_error_events_fingerprint'), ['fingerprint'], unique=True)
        batch_op.create_index(batch_op.f('ix_error_events_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_events_route'), ['route'], unique=False)
        batch_op.create_index(batch_op.f('ix_error_events_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('topic', sa.String(length=48), nullable=False),
    sa.Column('subject', sa.String(length=240), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_read', ['user_id', 'read_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_topic'), ['topic'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('tagline', sa.String(length=240), nullable=True),
    sa.Column('price_monthly_inr', sa.Integer(), nullable=False),
    sa.Column('price_annual_inr', sa.Integer(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('quotas', sa.JSON(), nullable=False),
    sa.Column('limits', sa.JSON(), nullable=False),
    sa.Column('trial_days', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plans_tier'), ['tier'], unique=True)

    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('cost_basis', sa.String(length=24), nullable=False),
    sa.Column('benchmark', sa.String(length=32), nullable=False),
    sa.Column('max_position_size', sa.Float(), nullable=False),
    sa.Column('max_sector_weight', sa.Float(), nullable=False),
    sa.Column('margin_of_safety', sa.Float(), nullable=False),
    sa.Column('risk_free_rate', sa.Float(), nullable=False),
    sa.Column('target_positions', sa.Integer(), nullable=False),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_portfolio_owner_name')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_owner_id'), ['owner_id'], unique=False)

    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('traded_value', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'as_of', name='uq_price_ticker_date')
    )
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_history_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_history_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_price_ticker_date', ['ticker', 'as_of'], unique=False)

    op.create_table('request_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('route', sa.String(length=160), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('status_class', sa.String(length=4), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('total_ms', sa.Float(), nullable=False),
    sa.Column('max_ms', sa.Float(), nullable=False),
    sa.Column('histogram', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bucket_start', 'route', 'method', 'status_class', name='uq_metric_bucket')
    )
    with op.batch_alter_table('request_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_request_metrics_bucket_start'), ['bucket_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_request_metrics_route'), ['route'], unique=False)

    op.create_table('schedule_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('every_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_state', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_state_kind'), ['kind'], unique=True)

    op.create_table('scoring_weight_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=64), nullable=True),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('derived_from', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key', 'owner', name='uq_profile_key_owner')
    )
    with op.batch_alter_table('scoring_weight_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_weight_profiles_owner'), ['owner'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('industry', sa.String(length=80), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('primary_colour', sa.String(length=9), nullable=True),
    sa.Column('report_disclaimer', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('storage_bytes', sa.Integer(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('ix_tenant_status', ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_tenants_status'), ['status'], unique=False)

    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name', name='uq_watchlist_owner_name')
    )
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlists_owner_id'), ['owner_id'], unique=False)

    op.create_table('ai_analyses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=96), nullable=False),
    sa.Column('prompt_key', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.Integer(), nullable=False),
    sa.Column('citation_keys', sa.JSON(), nullable=True),
    sa.Column('citation_coverage', sa.Float(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('guardrails_passed', sa.Boolean(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.create_index('ix_analysis_company_capability', ['company_id', 'capability'], unique=False)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=True),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.String(length=200), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('observed', sa.String(length=80), nullable=True),
    sa.Column('threshold', sa.String(length=80), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index('ix_alert_dedup', ['portfolio_id', 'rule_key', 'ticker', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_rule_key'), ['rule_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_ticker'), ['ticker'], unique=False)
        batch_op.create_index('ix_alert_open', ['portfolio_id', 'status', 'severity'], unique=False)

    op.create_table('alert_rule_overrides',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('rule_key', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('metric', sa.String(length=64), nullable=True),
    sa.Column('comparator', sa.String(length=12), nullable=True),
    sa.Column('is_custom', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'portfolio_id', 'rule_key', name='uq_alert_override')
    )
    with op.batch_alter_table('alert_rule_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_rule_overrides_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rule_overrides_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_rule_overrides_rule_key'), ['rule_key'], unique=False)

    op.create_table('allocation_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=20), nullable=False),
    sa.Column('bucket_key', sa.String(length=120), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'dimension', 'bucket_key', name='uq_target_bucket')
    )
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_targets_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key_id', sa.String(length=24), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('call_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_key_hash'), ['key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_key_id'), ['key_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_apikey_tenant_active', ['tenant_id', 'revoked_at'], unique=False)

    op.create_table('credit_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('agency', sa.String(length=80), nullable=False),
    sa.Column('rating', sa.String(length=24), nullable=False),
    sa.Column('outlook', sa.String(length=40), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.Column('instrument_class', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_ratings', schema=None) as batch_op:
        batch_op.create_index('ix_rating_company', ['company_id'], unique=False)

    op.create_table('debt_instruments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('instrument', sa.String(length=160), nullable=False),
    sa.Column('lender', sa.String(length=160), nullable=True),
    sa.Column('security', sa.String(length=24), nullable=False),
    sa.Column('rate_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('maturity_year', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('debt_instruments', schema=None) as batch_op:
        batch_op.create_index('ix_debt_company_year', ['company_id', 'fiscal_year'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=400), nullable=False),
    sa.Column('title', sa.String(length=400), nullable=True),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('file_format', sa.String(length=16), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('entity_count', sa.Integer(), nullable=False),
    sa.Column('fact_count', sa.Integer(), nullable=False),
    sa.Column('used_ocr', sa.Boolean(), nullable=False),
    sa.Column('ocr_pages', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Float(), nullable=False),
    sa.Column('avg_confidence', sa.Float(), nullable=False),
    sa.Column('duplicate_ratio', sa.Float(), nullable=False),
    sa.Column('embedding_spec', sa.String(length=80), nullable=True),
    sa.Column('processing_ms', sa.Float(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.String(length=64), nullable=True),
    sa.Column('doc_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'content_hash', name='uq_document_company_hash')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_document_company_status', ['company_id', 'status'], unique=False)
        batch_op.create_index('ix_document_company_type', ['company_id', 'doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_status'), ['status'], unique=False)

    op.create_table('financial_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('line_item', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('precedence', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'line_item', 'precedence', name='uq_fact_company_year_item_precedence')
    )
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.create_index('ix_fact_lookup', ['company_id', 'fiscal_year', 'line_item'], unique=False)

    op.create_table('forecasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('revenue_method', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('segments', sa.JSON(), nullable=True),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index('ix_forecast_company', ['company_id', 'status'], unique=False)

    op.create_table('invoices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('plan_tier', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('subtotal_paise', sa.Integer(), nullable=False),
    sa.Column('tax_paise', sa.Integer(), nullable=False),
    sa.Column('total_paise', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('net_flow', sa.Float(), nullable=False),
    sa.Column('position_count', sa.Integer(), nullable=False),
    sa.Column('benchmark_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'as_of', name='uq_snapshot_portfolio_date')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'), ['portfolio_id'], unique=False)

    op.create_table('portfolio_transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('txn_type', sa.String(length=20), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('taxes', sa.Float(), nullable=False),
    sa.Column('ratio_from', sa.Float(), nullable=True),
    sa.Column('ratio_to', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('external_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_transactions_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_transactions_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_transactions_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_transactions_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_transactions_txn_type'), ['txn_type'], unique=False)
        batch_op.create_index('ix_txn_portfolio_date', ['portfolio_id', 'trade_date', 'sequence'], unique=False)
        batch_op.create_index('ix_txn_portfolio_ticker', ['portfolio_id', 'ticker'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('theme', sa.String(length=12), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('superseded_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('analyst', sa.String(length=120), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('section_count', sa.Integer(), nullable=False),
    sa.Column('insufficient_count', sa.Integer(), nullable=False),
    sa.Column('block_count', sa.Integer(), nullable=False),
    sa.Column('chart_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('citation_coverage', sa.Float(), nullable=False),
    sa.Column('citation_clean', sa.Boolean(), nullable=False),
    sa.Column('audit', sa.JSON(), nullable=True),
    sa.Column('input_hash', sa.String(length=40), nullable=True),
    sa.Column('provenance', sa.JSON(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=True),
    sa.Column('build_ms', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'report_type', 'version', name='uq_report_version')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_report_company_type', ['company_id', 'report_type'], unique=False)
        batch_op.create_index('ix_report_owner_status', ['owner_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_ticker'), ['ticker'], unique=False)

    op.create_table('score_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('profile_key', sa.String(length=64), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=8), nullable=False),
    sa.Column('stars', sa.Float(), nullable=False),
    sa.Column('recommendation', sa.String(length=16), nullable=False),
    sa.Column('conviction', sa.String(length=16), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified_pct', sa.Float(), nullable=False),
    sa.Column('estimated_pct', sa.Float(), nullable=False),
    sa.Column('missing_pct', sa.Float(), nullable=False),
    sa.Column('category_scores', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'as_of', 'profile_key', name='uq_snapshot_company_date_profile')
    )
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_company_date', ['company_id', 'as_of'], unique=False)

    op.create_table('shareholding_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('promoter_indian', sa.Float(), nullable=False),
    sa.Column('promoter_foreign', sa.Float(), nullable=False),
    sa.Column('fii_fpi', sa.Float(), nullable=False),
    sa.Column('mutual_funds', sa.Float(), nullable=False),
    sa.Column('insurance', sa.Float(), nullable=False),
    sa.Column('banks_fis_aif', sa.Float(), nullable=False),
    sa.Column('government', sa.Float(), nullable=False),
    sa.Column('others_custodians', sa.Float(), nullable=False),
    sa.Column('promoter_pledged', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', 'quarter', name='uq_shareholding_period')
    )
    with op.batch_alter_table('shareholding_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_shareholding_company_period', ['company_id', 'fiscal_year', 'quarter'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('plan_tier', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('billing_period', sa.String(length=12), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('trial_ends_at', sa.Date(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quota_overrides', sa.JSON(), nullable=True),
    sa.Column('limit_overrides', sa.JSON(), nullable=True),
    sa.Column('feature_overrides', sa.JSON(), nullable=True),
    sa.Column('provider', sa.String(length=24), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=64), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_plan_tier'), ['plan_tier'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_tenant_id'), ['tenant_id'], unique=True)

    op.create_table('tenant_secrets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('hint', sa.String(length=16), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_secret_name')
    )
    with op.batch_alter_table('tenant_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_secrets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_counters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('quota', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('last_event_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'quota', 'period_start', name='uq_usage_counter_period')
    )
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_counters_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('usage_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('quota', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('cost_micros', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_events_api_key_id'), ['api_key_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_quota'), ['quota'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_events_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_usage_tenant_quota_time', ['tenant_id', 'quota', 'occurred_at'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_method', sa.String(length=16), nullable=False),
    sa.Column('mfa_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invited_by', sa.String(length=36), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_tenant_role', ['tenant_id', 'role'], unique=False)
        batch_op.create_index('ix_user_tenant_status', ['tenant_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('buy_below', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('conviction', sa.String(length=20), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('watchlist_id', 'ticker', name='uq_watch_entry_ticker')
    )
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watchlist_entries_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_entries_ticker'), ['ticker'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_entries_watchlist_id'), ['watchlist_id'], unique=False)

    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('paragraph', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('section_title', sa.String(length=200), nullable=True),
    sa.Column('token_estimate', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=40), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_document_page', ['document_id', 'page'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_fingerprint'), ['fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_page'), ['page'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_chunks_section'), ['section'], unique=False)

    op.create_table('document_entities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=400), nullable=False),
    sa.Column('normalised', sa.String(length=200), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('mentions', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_entities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_entities_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_entities_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_entities_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_entities_normalised'), ['normalised'], unique=False)
        batch_op.create_index('ix_entity_company_kind', ['company_id', 'kind'], unique=False)

    op.create_table('document_facts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('field_key', sa.String(length=60), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('text_value', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=True),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('promoted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_facts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_facts_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_facts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_facts_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_facts_field_key'), ['field_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_facts_period'), ['period'], unique=False)
        batch_op.create_index('ix_fact_company_field', ['company_id', 'field_key'], unique=False)
        batch_op.create_index('ix_fact_company_period', ['company_id', 'period'], unique=False)

    op.create_table('document_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_jobs_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_jobs_status'), ['status'], unique=False)
        batch_op.create_index('ix_job_status_priority', ['status', 'priority'], unique=False)

    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_source', sa.String(length=16), nullable=False),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'page_number', name='uq_page_document_number')
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('document_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('source_key', sa.String(length=220), nullable=False),
    sa.Column('target_key', sa.String(length=220), nullable=False),
    sa.Column('source_label', sa.String(length=400), nullable=False),
    sa.Column('target_label', sa.String(length=400), nullable=False),
    sa.Column('source_kind', sa.String(length=30), nullable=False),
    sa.Column('target_kind', sa.String(length=30), nullable=False),
    sa.Column('relation', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('pages', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'source_key', 'target_key', 'relation', name='uq_relation_edge')
    )
    with op.batch_alter_table('document_relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_relations_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relations_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relations_relation'), ['relation'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relations_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_relations_target_key'), ['target_key'], unique=False)
        batch_op.create_index('ix_relation_company_rel', ['company_id', 'relation'], unique=False)

    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_page', sa.Integer(), nullable=False),
    sa.Column('end_page', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_sections_kind'), ['kind'], unique=False)

    op.create_table('document_tables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=400), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('header', sa.JSON(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=True),
    sa.Column('merged', sa.JSON(), nullable=True),
    sa.Column('n_rows', sa.Integer(), nullable=False),
    sa.Column('n_cols', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_tables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_tables_document_id'), ['document_id'], unique=False)

    op.create_table('forecast_assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('forecast_id', sa.String(length=36), nullable=False),
    sa.Column('driver', sa.String(length=64), nullable=False),
    sa.Column('scenario', sa.String(length=16), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('by_year', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('citation', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['forecast_id'], ['forecasts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('forecast_id', 'driver', 'scenario', name='uq_assumption_driver_scenario')
    )
    with op.batch_alter_table('forecast_assumptions', schema=None) as batch_op:
        batch_op.create_index('ix_assumption_forecast', ['forecast_id', 'scenario'], unique=False)

    op.create_table('one_time_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('purpose', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('one_time_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_one_time_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_one_time_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_one_time_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_ott_user_purpose', ['user_id', 'purpose', 'consumed_at'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('replaced_by', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_family', ['family_id', 'revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_family_id'), ['family_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('report_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('fmt', sa.String(length=8), nullable=False),
    sa.Column('filename', sa.String(length=240), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('render_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'fmt', name='uq_artifact_report_format')
    )
    with op.batch_alter_table('report_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_artifacts_fmt'), ['fmt'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_artifacts_report_id'), ['report_id'], unique=False)

    op.create_table('report_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('timings', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_report_job_status', ['status', 'id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_jobs_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_jobs_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_jobs_status'), ['status'], unique=False)

    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('subject', sa.String(length=191), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('profile', sa.JSON(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_identity_provider_subject')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_identities_provider'))

    op.drop_table('user_identities')
    with op.batch_alter_table('report_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_report_jobs_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_jobs_owner_id'))
        batch_op.drop_index('ix_report_job_status')

    op.drop_table('report_jobs')
    with op.batch_alter_table('report_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_artifacts_report_id'))
        batch_op.drop_index(batch_op.f('ix_report_artifacts_fmt'))

    op.drop_table('report_artifacts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_session_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_family_id'))
        batch_op.drop_index('ix_refresh_family')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('one_time_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_ott_user_purpose')
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_one_time_tokens_purpose'))

    op.drop_table('one_time_tokens')
    with op.batch_alter_table('forecast_assumptions', schema=None) as batch_op:
        batch_op.drop_index('ix_assumption_forecast')

    op.drop_table('forecast_assumptions')
    with op.batch_alter_table('document_tables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_tables_document_id'))

    op.drop_table('document_tables')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_kind'))
        batch_op.drop_index(batch_op.f('ix_document_sections_document_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('document_relations', schema=None) as batch_op:
        batch_op.drop_index('ix_relation_company_rel')
        batch_op.drop_index(batch_op.f('ix_document_relations_target_key'))
        batch_op.drop_index(batch_op.f('ix_document_relations_source_key'))
        batch_op.drop_index(batch_op.f('ix_document_relations_relation'))
        batch_op.drop_index(batch_op.f('ix_document_relations_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_relations_company_id'))

    op.drop_table('document_relations')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    with op.batch_alter_table('document_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_job_status_priority')
        batch_op.drop_index(batch_op.f('ix_document_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_jobs_company_id'))

    op.drop_table('document_jobs')
    with op.batch_alter_table('document_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_company_period')
        batch_op.drop_index('ix_fact_company_field')
        batch_op.drop_index(batch_op.f('ix_document_facts_period'))
        batch_op.drop_index(batch_op.f('ix_document_facts_field_key'))
        batch_op.drop_index(batch_op.f('ix_document_facts_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_facts_company_id'))
        batch_op.drop_index(batch_op.f('ix_document_facts_category'))

    op.drop_table('document_facts')
    with op.batch_alter_table('document_entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_company_kind')
        batch_op.drop_index(batch_op.f('ix_document_entities_normalised'))
        batch_op.drop_index(batch_op.f('ix_document_entities_kind'))
        batch_op.drop_index(batch_op.f('ix_document_entities_document_id'))
        batch_op.drop_index(batch_op.f('ix_document_entities_company_id'))

    op.drop_table('document_entities')
    with op.batch_alter_table('document_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_chunks_section'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_page'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_document_chunks_document_id'))
        batch_op.drop_index('ix_chunk_document_page')

    op.drop_table('document_chunks')
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_watchlist_id'))
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_ticker'))
        batch_op.drop_index(batch_op.f('ix_watchlist_entries_company_id'))

    op.drop_table('watchlist_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_status'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('ix_user_tenant_status')
        batch_op.drop_index('ix_user_tenant_role')

    op.drop_table('users')
    with op.batch_alter_table('usage_events', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_tenant_quota_time')
        batch_op.drop_index(batch_op.f('ix_usage_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_usage_events_quota'))
        batch_op.drop_index(batch_op.f('ix_usage_events_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_usage_events_api_key_id'))

    op.drop_table('usage_events')
    with op.batch_alter_table('usage_counters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_counters_tenant_id'))

    op.drop_table('usage_counters')
    with op.batch_alter_table('tenant_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_secrets_tenant_id'))

    op.drop_table('tenant_secrets')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_plan_tier'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('shareholding_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_shareholding_company_period')

    op.drop_table('shareholding_snapshots')
    with op.batch_alter_table('score_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_company_date')

    op.drop_table('score_snapshots')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_ticker'))
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_report_type'))
        batch_op.drop_index(batch_op.f('ix_reports_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_reports_owner_id'))
        batch_op.drop_index(batch_op.f('ix_reports_input_hash'))
        batch_op.drop_index(batch_op.f('ix_reports_company_id'))
        batch_op.drop_index('ix_report_owner_status')
        batch_op.drop_index('ix_report_company_type')

    op.drop_table('reports')
    with op.batch_alter_table('portfolio_transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_portfolio_ticker')
        batch_op.drop_index('ix_txn_portfolio_date')
        batch_op.drop_index(batch_op.f('ix_portfolio_transactions_txn_type'))
        batch_op.drop_index(batch_op.f('ix_portfolio_transactions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_portfolio_transactions_ticker'))
        batch_op.drop_index(batch_op.f('ix_portfolio_transactions_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_transactions_company_id'))

    op.drop_table('portfolio_transactions')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_portfolio_snapshots_as_of'))

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_status'))
        batch_op.drop_index('ix_invoice_tenant_status')

    op.drop_table('invoices')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index('ix_forecast_company')

    op.drop_table('forecasts')
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.drop_index('ix_fact_lookup')

    op.drop_table('financial_facts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_status'))
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))
        batch_op.drop_index('ix_document_company_type')
        batch_op.drop_index('ix_document_company_status')

    op.drop_table('documents')
    with op.batch_alter_table('debt_instruments', schema=None) as batch_op:
        batch_op.drop_index('ix_debt_company_year')

    op.drop_table('debt_instruments')
    with op.batch_alter_table('credit_ratings', schema=None) as batch_op:
        batch_op.drop_index('ix_rating_company')

    op.drop_table('credit_ratings')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_apikey_tenant_active')
        batch_op.drop_index(batch_op.f('ix_api_keys_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_key_hash'))

    op.drop_table('api_keys')
    with op.batch_alter_table('allocation_targets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_targets_portfolio_id'))

    op.drop_table('allocation_targets')
    with op.batch_alter_table('alert_rule_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_rule_overrides_rule_key'))
        batch_op.drop_index(batch_op.f('ix_alert_rule_overrides_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_alert_rule_overrides_owner_id'))

    op.drop_table('alert_rule_overrides')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_open')
        batch_op.drop_index(batch_op.f('ix_alert_events_ticker'))
        batch_op.drop_index(batch_op.f('ix_alert_events_status'))
        batch_op.drop_index(batch_op.f('ix_alert_events_severity'))
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_key'))
        batch_op.drop_index(batch_op.f('ix_alert_events_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_owner_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_company_id'))
        batch_op.drop_index(batch_op.f('ix_alert_events_category'))
        batch_op.drop_index('ix_alert_dedup')

    op.drop_table('alert_events')
    with op.batch_alter_table('ai_analyses', schema=None) as batch_op:
        batch_op.drop_index('ix_analysis_company_capability')

    op.drop_table('ai_analyses')
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlists_owner_id'))

    op.drop_table('watchlists')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_status'))
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))
        batch_op.drop_index('ix_tenant_status')

    op.drop_table('tenants')
    with op.batch_alter_table('scoring_weight_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_weight_profiles_owner'))

    op.drop_table('scoring_weight_profiles')
    with op.batch_alter_table('schedule_state', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_state_kind'))

    op.drop_table('schedule_state')
    with op.batch_alter_table('request_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_request_metrics_route'))
        batch_op.drop_index(batch_op.f('ix_request_metrics_bucket_start'))

    op.drop_table('request_metrics')
    with op.batch_alter_table('price_history', schema=None) as batch_op:
        batch_op.drop_index('ix_price_ticker_date')
        batch_op.drop_index(batch_op.f('ix_price_history_ticker'))
        batch_op.drop_index(batch_op.f('ix_price_history_as_of'))

    op.drop_table('price_history')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_owner_id'))

    op.drop_table('portfolios')
    with op.batch_alter_table('plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plans_tier'))

    op.drop_table('plans')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_topic'))
        batch_op.drop_index(batch_op.f('ix_notifications_tenant_id'))
        batch_op.drop_index('ix_notification_user_read')

    op.drop_table('notifications')
    with op.batch_alter_table('error_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_error_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_error_events_route'))
        batch_op.drop_index(batch_op.f('ix_error_events_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_error_events_fingerprint'))

    op.drop_table('error_events')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index('ix_company_sector_mcap')
        batch_op.drop_index(batch_op.f('ix_companies_ticker'))
        batch_op.drop_index(batch_op.f('ix_companies_sector'))
        batch_op.drop_index(batch_op.f('ix_companies_name'))
        batch_op.drop_index(batch_op.f('ix_companies_industry'))

    op.drop_table('companies')
    with op.batch_alter_table('billing_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_billing_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_billing_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_billing_events_event_id'))

    op.drop_table('billing_events')
    with op.batch_alter_table('benchmark_levels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_levels_symbol'))
        batch_op.drop_index(batch_op.f('ix_benchmark_levels_as_of'))

    op.drop_table('benchmark_levels')
    with op.batch_alter_table('backup_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backup_records_finished_at'))

    op.drop_table('backup_records')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_job_tenant_kind')
        batch_op.drop_index('ix_job_poll')
        batch_op.drop_index(batch_op.f('ix_background_jobs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_run_after'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_idempotency_key'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_tenant_time')
        batch_op.drop_index(batch_op.f('ix_audit_logs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_severity'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_category'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_category_time')

    op.drop_table('audit_logs')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index('ix_usage_owner_provider')
        batch_op.drop_index(batch_op.f('ix_ai_usage_owner'))

    op.drop_table('ai_usage')
    with op.batch_alter_table('ai_prompts', schema=None) as batch_op:
        batch_op.drop_index('ix_prompt_active')
        batch_op.drop_index(batch_op.f('ix_ai_prompts_key'))

    op.drop_table('ai_prompts')
    # ### end Alembic commands ###
